---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[my_test::default]
    attributes:
