name 'my_test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures my_test'
long_description 'Installs/Configures my_test'
version '0.1.0'

depends 'chef_handler'
depends 'ohai'
